In [5]:
from pandas import Series, DataFrame
import numpy as np
import pandas as pd

In [6]:
obj = Series([4, 7, -5, 3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [11]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
obj2['a']

-5

In [15]:
obj2['d']

4

In [16]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [17]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [18]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [19]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2

True

In [21]:
'e' in obj2

False

In [22]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [23]:
sdata

{'Ohio': 35000, 'Oregon': 16000, 'Texas': 71000, 'Utah': 5000}

In [24]:
obj3 = Series(sdata)

In [25]:
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [26]:
states = {'California', 'Ohio', 'Oregon', 'Texas'}

In [27]:
states

{'California', 'Ohio', 'Oregon', 'Texas'}

In [28]:
obj4 = Series(sdata, index=states)

In [29]:
obj4

Oregon        16000.0
Ohio          35000.0
California        NaN
Texas         71000.0
dtype: float64

In [30]:
pd.isnull(obj4)

Oregon        False
Ohio          False
California     True
Texas         False
dtype: bool

In [31]:
pd.isnull(obj4)

Oregon        False
Ohio          False
California     True
Texas         False
dtype: bool

In [32]:
obj4.isnull()

Oregon        False
Ohio          False
California     True
Texas         False
dtype: bool

In [33]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [35]:
obj4.index.name = 'state'

In [36]:
obj4

state
Oregon        16000.0
Ohio          35000.0
California        NaN
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [39]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [40]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [41]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)

In [42]:
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [43]:
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [44]:
frame2 = DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [45]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [46]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [49]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [50]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2.debt = 16.5

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [53]:
frame2.debt = np.arange(5.)

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [57]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [58]:
frame2['debt'] = val

In [59]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [60]:
frame2['eastern'] = frame2.state == 'Ohio'

In [61]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [62]:
frame2.eastern = frame2.state == 'Ohio'

In [63]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [65]:
frame2.loc['one']

year       2000
state      Ohio
pop         1.5
debt        NaN
eastern    True
Name: one, dtype: object

In [67]:
del frame2['eastern']

In [68]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [69]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
      'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [70]:
frame3 = DataFrame(pop)

In [71]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [72]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [76]:
frame3.name = 'Frame3'; frame3.index.name = 'index_name'; frame3.columns.name = 'Columns Name'

In [77]:
frame3

Columns Name  Nevada  Ohio
index_name                
2000             NaN   1.5
2001             2.4   1.7
2002             2.9   3.6

In [80]:
DataFrame(pop, index=[2001, 2002, 2004])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2004     NaN   NaN

In [81]:
frame3

Columns Name  Nevada  Ohio
index_name                
2000             NaN   1.5
2001             2.4   1.7
2002             2.9   3.6

In [82]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

Nevada  Ohio
index_name              
2000           NaN   1.5
2001           2.4   1.7

In [84]:
frame3['Ohio'][0:-1]

index_name
2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [88]:
frame3['Ohio'][0:-1]

index_name
2000    1.5
2001    1.7
Name: Ohio, dtype: float64

In [89]:
frame3

Columns Name  Nevada  Ohio
index_name                
2000             NaN   1.5
2001             2.4   1.7
2002             2.9   3.6

In [90]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='index_name')

In [91]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='Columns Name')

In [92]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [93]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [94]:
obj = Series(range(3), index=['a', 'b', 'c'])

In [95]:
obj

a    0
b    1
c    2
dtype: int32

In [96]:
index = obj.index

In [97]:
index

Index(['a', 'b', 'c'], dtype='object')

In [98]:
index[1:]

Index(['b', 'c'], dtype='object')

In [99]:
index[0]

'a'

In [100]:
index = pd.Index(np.arange(3))

In [101]:
index

Int64Index([0, 1, 2], dtype='int64')

In [102]:
obj2 = Series([1.5, -2.5, 0], index=index)

In [103]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [104]:
obj2.index is index

True

In [105]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='index_name')

In [106]:
frame3

Columns Name  Nevada  Ohio
index_name                
2000             NaN   1.5
2001             2.4   1.7
2002             2.9   3.6

In [107]:
'Ohio' in frame3.columns

True

In [108]:
2003 in frame3.index

False

In [109]:
obj = Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [110]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [112]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [113]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [114]:
obj.reindex(['a', 'b', 'c', 'd', 'e'], fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [115]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [116]:
obj3 = Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [117]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [118]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [119]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [120]:
frame = DataFrame(np.arange(9).reshape(3, 3), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [121]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [122]:
states = ['Texas', 'Utah', 'California']

In [123]:
frame2 = frame.reindex(columns=states)

In [124]:
frame2

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [125]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [130]:
frame.reindex(index=['a', 'b', 'c', 'd'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [132]:
frame.reindex(index=['a', 'b', 'c', 'd'], method='ffill')

Ohio  Texas  California
a     0      1           2
b     0      1           2
c     3      4           5
d     6      7           8

In [134]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [141]:
frame.loc[['a', 'b', 'c', 'd'], states]

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [144]:
obj = Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])

In [145]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [146]:
new_obj = obj.drop('c')

In [147]:
new_obj

a    0
b    1
d    3
e    4
dtype: int32

In [148]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [149]:
obj.drop(['d', 'c'])

a    0
b    1
e    4
dtype: int32

In [150]:
data = DataFrame(np.arange(16).reshape(4, 4), index=['Ohio', 'Colordao', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [151]:
data

one  two  three  four
Ohio        0    1      2     3
Colordao    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [152]:
data.drop(['Colordao', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colordao    4      6     7
Utah        8     10    11
New York   12     14    15

In [155]:
data

one  two  three  four
Ohio        0    1      2     3
Colordao    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15